name: Kanban Project Automation

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  move_issue_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to 'In Progress'
        uses: actions/github-script@v6
        with:
          script: |
            const projectName = "Devops-agile";
            const columnName = "In Progress";

            // Fetch all projects for the repository
            const { data: projects } = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Find the project by name
            const project = projects.find(p => p.name === projectName);
            if (!project) {
              throw new Error(`Project "${projectName}" not found`);
            }

            // Fetch all columns for the project
            const { data: columns } = await github.rest.projects.listColumns({
              project_id: project.id,
            });

            // Find the column by name
            const column = columns.find(c => c.name === columnName);
            if (!column) {
              throw new Error(`Column "${columnName}" not found`);
            }

            // Move the linked issue to the column
            const issueNumber = context.payload.pull_request.body.match(/#\d+/)[0].substring(1);
            await github.rest.projects.createCard({
              column_id: column.id,
              content_id: context.payload.pull_request.id,
              content_type: "Issue",
            });